version: "3.8"
services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    network_mode: "host"
    cap_add:
      - NET_ADMIN
    volumes:
      - ./config:/config
      - /lib/modules:/lib/modules
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jakarta
    restart: unless-stopped
