CREATE TABLE IF NOT EXISTS nas_status (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nasname VARCHAR(64) NOT NULL,
  status ENUM('up','down') DEFAULT 'down',
  last_check TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
