FROM debian:bullseye

# Install dependencies
RUN apt-get update && apt-get install -y \
    lsb-release \
    ca-certificates \
    apt-transport-https \
    software-properties-common \
    gnupg \
    wget \
    php \
    php-xml \
    php-pear \
    php-mysql \
    apache2 \
    libapache2-mod-php \
    && rm -rf /var/lib/apt/lists/*

# Update pear channel & install DB
RUN pear channel-update pear.php.net \
    && pear install DB

# Enable Apache & PHP
RUN a2enmod php7.4 || true
RUN a2enmod rewrite

# Copy daloRADIUS source code
WORKDIR /var/www/html
COPY ./daloradius/ /var/www/html/

# Set permissions
RUN chown -R www-data:www-data /var/www/html \
    && chmod -R 755 /var/www/html

# Expose port
EXPOSE 80

# Start Apache in foreground
CMD ["apachectl", "-D", "FOREGROUND"]
